fn main() {
    // Listing the app's commands generates an `allow-<command>` permission for each, so a command
    // is callable only when a capability grants it (capabilities/main.json, or debug.rs at runtime).
    // Release builds define the debug permissions too but neither grant nor register those commands:
    // the build writes the permissions to permissions/autogenerated/, shared by both profiles.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "list",
            "read",
            "save",
            "create",
            "load_preferences",
            "save_preferences",
            "debug_log",
            "debug_window",
            "debug_snapshot",
        ]),
    ))
    .expect("failed to run the Tauri build script");
}
